env:
  browser: true
  commonjs: true
  es2021: true
  node: true
extends:
  eslint: recommended
  plugin: jest/recommended
  plugin: jest/style
overrides: []
parserOptions:
  ecmaVersion: latest
rules: {}
